config/routes.rb
ColorElephant::Application.routes.draw do

  resources :users

  match '/auth/:provider/callback' => 'user_oauth#create', :as => :callback
  match '/auth/failure' => 'user_oauth#failure', :as => :failure
  match '/auth/facebook' => 'user_oauth#create', :as => :fb_login
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'update_fb_status' => "users#update_fb_status", :as => :update_fb_status
  root :to => 'user_sessions#new'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :feed_id, :story, :feed_creation_time, :comment_count, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation,:facebook_uid, :password_salt, :crypted_password, :persistence_token,:access_token,:fb_profile_pic,:oauth_token,:oauth_token_secret, :relationship_status
  has_many :feeds, :dependent => :destroy
  acts_as_authentic do |c|
    c.validate_email_field = false
    c.validate_password_field = false
  end

  def self.find_or_create_from_oauth(auth_hash)
    provider = auth_hash["provider"]
    uid = auth_hash["uid"]
    case provider
      when 'facebook'
        if user = self.find_by_email(auth_hash["info"]["email"])
          user.update_user_from_facebook(auth_hash)
          return user
        elsif user = self.find_by_facebook_uid(uid)
          return user
        else
          return self.create_user_from_facebook(auth_hash)
        end
    end
  end

  def self.create_user_from_facebook(auth_hash)
    self.create({
                    :facebook_uid => auth_hash["uid"],
                    :access_token => auth_hash['credentials']['token'],
                    :first_name => auth_hash["info"]["first_name"] + " " + auth_hash["info"]["last_name"],
                    :email => auth_hash["info"]["email"],
                    :crypted_password => "facebook",
                    :password_salt => "facebook",
                    :persistence_token => "facebook",
                    :fb_profile_pic => auth_hash.info.image,
                    :relationship_status => auth_hash['extra']['raw_info']['relationship_status']
                })
  end

  def update_user_from_facebook(auth_hash)
    self.update_attributes({
                               :facebook_uid => auth_hash["uid"]
                           })
  end

  def clear_feeds
    self.feeds.each{|f| f.destroy}
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user_session, :current_user

  private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end
end

app/controllers/user_oauth_controller.rb
class UserOauthController < ApplicationController
  def create
    @user = User.find_or_create_from_oauth(auth_hash)
    current_user = @user
    if current_user
      UserSession.create(current_user, true)
        if current_user.facebook_uid
          @id = current_user.facebook_uid
        end
      update_user_feeds
      redirect_to users_path
    else
      redirect_to root_url, :flash => {:error => "Not authorized"}
    end
  end
  
  def failure
    redirect_to root_url, :flash => {:error => "Not authorized. #{params[:message]}"}
  end

  protected

  def update_user_feeds
    current_user.clear_feeds
    @graph = Koala::Facebook::GraphAPI.new(current_user.access_token)
    @feeds = @graph.get_connections("me", "feed")
    @feeds.each do |feed|
      Feed.create(:user_id => current_user.id,:feed_id => feed['id'], :story => feed['story'], :feed_creation_time => feed['created_time'], :comment_count => feed['comments']['count'])
    end
  end

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    if !current_user
      @user_session = UserSession.new
    else
      redirect_to users_url
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Successfully Logout!"
    redirect_to :controller => "user_sessions", :action => "new"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def update_fb_status
    @id = current_user.facebook_uid
    @graph = Koala::Facebook::GraphAPI.new(current_user.access_token)
    @graph.put_wall_post(params[:status],{:name => 'ad'},@id)
    render :json => true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My FB Feeds</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="body_bg_color">
<div class="container">
  <div class="hgt_100">
    <h2 class="flt-lt">My FB Feeds</h2>
    <%if current_user%>
        <div class="flt-rt">
          <table>
            <tr>
              <td rowspan="2"><%=image_tag current_user.fb_profile_pic, :class => "user_image"%></td>
              <td class="user_name">Welcome <%=current_user.first_name.to_s%></td>
            </tr>
            <tr>
              <td><%= link_to "Sign out",  {:controller => "user_sessions",:action => "destroy"},:class => "signout", :id => "sign_out"%></td>
            </tr>
          </table>
        </div>
    <%end%>
  </div>
  <div style="color:red;" align="center" id="error_div"><%= flash[:error] %></div>
  <div style="color:green;" align="center" id="success_div"><%= flash[:notice] %></div>
  <%= yield %>
</div>
<script type="text/javascript">
    var fb_app_id = "<%= APP_CONFIG['FB_APP_ID'] %>"
    var callback_url = "<%= APP_CONFIG['url'] %>"
    function fbConnect()
    {
        mylink = "https://graph.facebook.com/oauth/authorize?client_id="+fb_app_id+"&display=popup&redirect_uri="+callback_url+"/auth/facebook&scope=email,offline_access,user_birthday,user_about_me,user_hometown,user_location,user_online_presence,user_photos,publish_stream";
        if (! window.focus)return true;
        var href;

        window.open(mylink, 'facebook', 'width=640,height=340,scrollbars=no');
        return false;
    }

</script>
</body>
</html>

app/views/user_sessions/new.html.erb
<div class="login_div">
  Hi Guest!<br/>
  Please sign up or login with your facebook account to get your latest feeds.
  <div class="clear"></div>
  <div class="fb_login_button"><%= link_to_function image_tag('fb_login.png'),"fbConnect();", :class=>"facebookLoginWindow" %></div>
</div>

app/views/users/index.html.erb
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.8.3.js"></script>
<script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
<script>
    window.opener.location = "/";
    window.close();
</script>
<script>
    $(function() {
        $( "#tabs" ).tabs();
    });
</script>
<div id="tabs">
  <ul>
    <li><a href="#home">Home</a></li>
    <li><a href="#tabs-1">Tab 1</a></li>
    <li><a href="#tabs-2">Tab 2</a></li>
    <li><a href="#tabs-3">Tab 3</a></li>
  </ul>
  <div id="home">
     <h3>This is your Home Page.</h3>
  </div>
  <div id="tabs-1">
    <h3>Welcome <%= current_user.first_name %></h3>
    <p>
      Your Relationship Status : <span style="color: red;"><%= current_user.relationship_status %></span>
    </p>
  </div>
  <div id="tabs-2">
    <h3>Update Your Facebook status</h3>
    <%= text_area_tag :new_status,"",:placeholder => "Whats on your mind?", :class => "new_status_field" %>
    <%= button_to_function "Post on Facebook","update_facebook_status()" %>
  </div>
  <div id="tabs-3">
    <% current_user.feeds.each do |feed| %>
        <div class="feed_div">
          <table width="100%">
            <tr>
                <td colspan="2"><%= feed.story %></td>
            </tr>
            <tr>
              <td align="left" class="feed_time"><%= distance_of_time_in_words_to_now(Time.parse(feed.feed_creation_time)) %> ago</td>
              <td align="right" class="feed_time"><%= feed.comment_count %> comments</td>
            </tr>
          </table>
        </div>
    <% end %>
  </div>
</div>

<script>
  function update_facebook_status() {
      $.ajax({
         url : "<%= update_fb_status_path %>",
         data : "status=" + $('#new_status').val(),
         success : function(data){
               $('#success_div').html("Your Facebook status has been updated successfully!");
               $('#new_status').val('');
          }
     });
  }
</script>